# Generated by Django 5.2.5 on 2025-08-28 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fotografia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("legenda", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("foto", models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/")),
                ("publicada", models.BooleanField(default=False)),
                (
                    "data_fotografia",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
            ],
        ),
    ]
