# Generated by Django 5.2.5 on 2025-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0002_categoria_alter_fotografia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="legenda",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
