# Generated by Django 5.2.5 on 2025-10-08 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0004_album_fotografia_album"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"verbose_name": "Álbum", "verbose_name_plural": "Álbuns"},
        ),
        migrations.AddField(
            model_name="album",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Criado em",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="album",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fotografia_album",
                to="galeria.album",
                verbose_name="Álbum",
            ),
        ),
    ]
