# Generated by Django 5.2.5 on 2025-10-08 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0005_alter_album_options_album_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="galeria.album",
                verbose_name="Álbum",
            ),
        ),
    ]
