# Generated by Django 5.2.5 on 2025-10-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0006_alter_fotografia_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="album_categoria",
                to="galeria.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
