# Generated by Django 5.2.5 on 2025-10-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0007_album_categoria_alter_fotografia_publicada"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
