# Generated by Django 5.2.5 on 2025-10-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0008_album_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
