# Generated by Django 5.2.5 on 2025-10-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0009_album_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="defaultPitch",
            field=models.CharField(
                default="0deg",
                help_text='Inclinação vertical inicial da câmera. Exemplos: "0deg" (horizonte), "45deg" (olhando para cima), "-45deg" (olhando para baixo)',
                max_length=20,
                verbose_name="Inclinação Vertical Inicial",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="defaultYaw",
            field=models.CharField(
                default="0deg",
                help_text='Direção horizontal inicial da câmera ao carregar. Exemplos: "0deg" (frente), "90deg" (direita), "-90deg" (esquerda), "180deg" (trás)',
                max_length=20,
                verbose_name="Rotação Horizontal Inicial",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="sphereCorrection_pan",
            field=models.CharField(
                default="0deg",
                help_text='Corrige rotação horizontal da foto. Use valores positivos para rotacionar à direita, negativos para esquerda. Ex: "10deg", "-15deg"',
                max_length=20,
                verbose_name="Correção Horizontal (Pan)",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="sphereCorrection_roll",
            field=models.CharField(
                default="0deg",
                help_text='Corrige foto torta/rotacionada. Valores positivos rotacionam no sentido horário, negativos anti-horário. Ex: "15deg", "-20deg"',
                max_length=20,
                verbose_name="Correção de Rotação (Roll)",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="sphereCorrection_tilt",
            field=models.CharField(
                default="0deg",
                help_text='Corrige inclinação vertical da foto. Valores positivos inclinam para cima, negativos para baixo. Ex: "5deg", "-10deg"',
                max_length=20,
                verbose_name="Correção Vertical (Tilt)",
            ),
        ),
    ]
