# Generated by Django 5.2.5 on 2026-09-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0010_album_defaultpitch_album_defaultyaw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="inverterSentidoStreetView",
            field=models.BooleanField(default=False),
        ),
    ]
