# Generated by Django 5.2.5 on 2026-09-15 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0011_album_invertersentidostreetview"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="arquivo_kml",
            field=models.FileField(
                blank=True,
                help_text="Arquivo .kml com o trajeto ou os pontos do álbum (opcional)",
                upload_to="kml/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["kml"]
                    )
                ],
                verbose_name="Arquivo KML",
            ),
        ),
    ]
