# Generated by Django 5.2.5 on 2026-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0012_album_arquivo_kml"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="ordenar_fotos_por",
            field=models.CharField(
                choices=[
                    ("nome", "Nome"),
                    ("-data_fotografia", "Data crescente"),
                    ("data_fotografia", "Data decrescente"),
                ],
                default="nome",
                max_length=30,
                verbose_name="Ordenar fotos por",
            ),
        ),
    ]
