# Generated by Django 5.2.5 on 2026-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0013_categoria_ordenar_fotos_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="mostrar_data",
            field=models.BooleanField(
                default=False, verbose_name="Mostrar data das fotos"
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="ordenar_fotos_por",
            field=models.CharField(
                choices=[
                    ("nome", "Nome"),
                    ("-data_fotografia", "Data Decrescente"),
                    ("data_fotografia", "Data Crescente"),
                ],
                default="nome",
                max_length=30,
                verbose_name="Ordenar fotos por",
            ),
        ),
    ]
