# Generated by Django 5.2.5 on 2026-10-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0014_categoria_mostrar_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fotografia",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="mostrar_data",
            field=models.BooleanField(
                default=False, verbose_name="Mostrar data nas fotos"
            ),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="galeria.album",
                verbose_name="Álbum 360",
            ),
        ),
    ]
