# Generated by Django 5.2.5 on 2026-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0015_fotografia_latitude_fotografia_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="imagem_compartilhamento",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to="og/",
                verbose_name="Imagem de compartilhamento (gerada automaticamente)",
            ),
        ),
    ]
